music_tools_instrument:
    resource: MusicTools\InstrumentBundle\Controller\InstrumentController
    type:     rest

music_tools_instrument_type:
    resource: MusicTools\InstrumentBundle\Controller\InstrumentTypeController
    type:     rest

music_tools_instrument_template:
    type:     rest
    parent:   music_tools_instrument_type
    resource: MusicTools\InstrumentBundle\Controller\InstrumentTemplateController
