imports:
    - { resource: common.yml }

bundles:
    - Symfony\Bundle\WebProfilerBundle\WebProfilerBundle
    - Sensio\Bundle\DistributionBundle\SensioDistributionBundle
    - Sensio\Bundle\GeneratorBundle\SensioGeneratorBundle
