imports:
    - { resource: common.yml }

bundles:
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle        : true
    Sensio\Bundle\DistributionBundle\SensioDistributionBundle : true
    Sensio\Bundle\GeneratorBundle\SensioGeneratorBundle       : true
