language: php

php:
  - 5.6
  - 7.0

install:
  # Create parameters file
  - cp app/config/parameters.yml.dist app/config/parameters.yml

  # Get server dependencies
  - composer self-update
  - composer update --prefer-source -o

script: php bin/phpunit --configuration phpunit.xml --coverage-text