language: php

php:
  - 5.6
  - 7.0

install:
  # Create parameters file
  - cp app/config/parameters.yml.dist app/config/parameters.yml

  # Get server dependencies
  - composer self-update
  - composer update --prefer-source -o

  # Configure test environment
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:update --force --env=test
  - php bin/console doctrine:fixtures:load --no-interaction --env=test
  - pwd

script: php bin/phpunit