language: php

php:
  - 5.6
  - 7.0

install:
  # Create parameters file
  - cp app/config/parameters.yml.dist app/config/parameters.yml

  # Get server dependencies
  - composer self-update
  - composer update --prefer-source -o

  # Configure test environment
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:update --force --env=test
  - php bin/console doctrine:fixtures:load --no-interaction --env=test

script:
  # Check the Coding Standards with PHP CS Fixer
  - php bin/php-cs-fixer fix src/ --dry-run --diff --verbose

  # Run Sensio Insight analysis
  - php bin/insight analysis 74bd74a9-b6fc-4b4e-9eb6-146748ab49db --no-interaction --verbose

  # Run tests suite vith PHPUnit
  - php bin/phpunit --verbose