# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"

        entity_managers:
            default:
                metadata_cache_driver: %doctrine_cache_driver%
                result_cache_driver:   %doctrine_cache_driver%
                query_cache_driver:    %doctrine_cache_driver%

                auto_mapping: true
                mappings:
                    # Doctrine extension Translatable
                    gedmo_translatable:
                        type:      annotation
                        prefix:    Gedmo\Translatable\Entity
                        dir:       "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                        is_bundle: false

                    # Doctrine extension Loggable
                    gedmo_loggable:
                        type:      annotation
                        prefix:    Gedmo\Loggable\Entity
                        dir:       "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                        is_bundle: false
