framework:
    # I18N configuration
    translator:
        fallbacks:  [ "%locale%" ]
    default_locale: "%locale%"

    validation:
        cache: %framework_cache_validation%
    serializer:
        cache: %framework_cache_serializer%

    # Security token
    secret:                  "%secret%"

    # Router configuration
    router:
        resource:            "%kernel.root_dir%/config/routing/%kernel.environment%.yml"
        strict_requirements: %kernel.debug%

    # Forms configuration
    form:                    ~
    csrf_protection:         ~
    validation:
        enable_annotations:  true

    # Templating configuration
    templating:
        engines:             [ "php" ]

    trusted_proxies:         ~

    # Session configuration
    session:
        name:                "%app_name%"
        handler_id:          session.handler.native_file
        save_path:           "%kernel.root_dir%/sessions"

    fragments:               ~
    http_method_override:    true

    # Profiler configuration
    profiler:
        enabled:             %kernel.debug%
