# moved into LocalizationBundle
stof_doctrine_extensions:
    default_locale: %locale%
    translation_fallback: true
    orm:
        default:
            translatable: true
            loggable:     true