# Twig Configuration (moved into UserInterfaceBundle)
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:      ['bootstrap_3_layout.html.twig']
    form:
        resources:
            - 'ElorfinUserInterfaceBundle:Form:fields.html.twig'
