imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

# Framework Configuration
framework:
    # Translator configuration
    translator:
        fallbacks:   [ "%locale%" ]
    default_locale:  "%locale%"

    secret:          "%secret%"

    # Router configuration
    router:
        resource:            "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%

    # Forms configuration
    form:            ~
    csrf_protection: ~
    validation:
        enable_annotations: true

    # Templating configuration
    templating:
        engines: ['php']

    fragments:       ~
    http_method_override: true
    trusted_hosts:   ~
    trusted_proxies: ~

    # Sessions configuration
    session:
        name:        "%app_name%"
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
