imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

# moved into LocalizationBundle
jms_i18n_routing:
    default_locale: %locale%
    locales:        %locales_available%
    strategy:       prefix_except_default

# moved into LocalizationBundle
stof_doctrine_extensions:
    default_locale: %locale%
    translation_fallback: true
    orm:
        default:
            translatable: true
            loggable:     true

framework:
    #esi:             ~

    # moved into LocalizationBundle
    translator:      { fallbacks: ["%locale%"] }
    default_locale:  "%locale%"


    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }

    # moved into UserInterfaceBundle
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme



    trusted_proxies: ~
    session:
        name: "%app_name%"
        handler_id: session.handler.native_file
        save_path:  "%kernel.root_dir%/sessions"
    fragments:       ~
    http_method_override: true

# Twig Configuration (moved into UserInterfaceBundle)
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes: ['bootstrap_3_layout.html.twig']
    form:
        resources:
            - 'ElorfinUserInterfaceBundle:Form:fields.html.twig'

# Assetic Configuration (moved into UserInterfaceBundle)
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    filters:
        cssrewrite: ~
        lessphp:
            file: '%kernel.root_dir%/../vendor/oyejorge/less.php/lessc.inc.php'
            apply_to: '\.less$'
        cssmin:
            file: '%kernel.root_dir%/../vendor/natxet/CssMin/src/CssMin.php'
            apply_to: '\.css$|\.less$'
        jsmin:
            file: '%kernel.root_dir%/../vendor/werkint/jsmin/JsMin/Minify.php'
            apply_to: '\.js$|\.twigjs$'

    assets:
        # Publish FontAwesome font files
        font-awesome-otf:
            inputs: '%kernel.root_dir%/../vendor/fortawesome/font-awesome/fonts/FontAwesome.otf'
            output: 'fonts/FontAwesome.otf'
        font-awesome-eot:
            inputs: '%kernel.root_dir%/../vendor/fortawesome/font-awesome/fonts/fontawesome-webfont.eot'
            output: 'fonts/fontawesome-webfont.eot'
        font-awesome-svg:
            inputs: '%kernel.root_dir%/../vendor/fortawesome/font-awesome/fonts/fontawesome-webfont.svg'
            output: 'fonts/fontawesome-webfont.svg'
        font-awesome-ttf:
            inputs: '%kernel.root_dir%/../vendor/fortawesome/font-awesome/fonts/fontawesome-webfont.ttf'
            output: 'fonts/fontawesome-webfont.ttf'
        font-awesome-woff:
            inputs: '%kernel.root_dir%/../vendor/fortawesome/font-awesome/fonts/fontawesome-webfont.woff'
            output: 'fonts/fontawesome-webfont.woff'

        # Publish Glyphicon font files
        glyphicon-eot:
            inputs: '%kernel.root_dir%/../vendor/twbs/bootstrap/fonts/glyphicons-halflings-regular.eot'
            output: 'fonts/glyphicons-halflings-regular.eot'
        glyphicon-svg:
            inputs: '%kernel.root_dir%/../vendor/twbs/bootstrap/fonts/glyphicons-halflings-regular.svg'
            output: 'fonts/glyphicons-halflings-regular.svg'
        glyphicon-ttf:
            inputs: '%kernel.root_dir%/../vendor/twbs/bootstrap/fonts/glyphicons-halflings-regular.ttf'
            output: 'fonts/glyphicons-halflings-regular.ttf'
        glyphicon-woff:
            inputs: '%kernel.root_dir%/../vendor/twbs/bootstrap/fonts/glyphicons-halflings-regular.woff'
            output: 'fonts/glyphicons-halflings-regular.woff'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"

        entity_managers:
            default:
                # Moved into LocalizationBundle
                auto_mapping: true

                mappings:
                    gedmo_translatable:
                        type: annotation
                        prefix: Gedmo\Translatable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                        is_bundle: false

                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                        is_bundle: false

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Moved into UserBundle
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Elorfin\UserBundle\Entity\User

# User interface configuration
elorfin_user_interface:
    loading_strategy: cdn
    libraries:
        # jQuery
        jquery:
            include: true
            #path:
            #    local:
            #        - { file: bundles/elorfinuserinterface/js/libraries/jquery/jquery.min.js }
            #    cdn:   //code.jquery.com/jquery-1.11.3.min.js

        # Bootstrap JS
        bootstrap_js:
            include: true
            #path:
            #    local:
            #        - { base_path: bootstrap/ }
            #    cdn:   https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js
            plugins:
                - transition
                - alert
                - button
                - carousel
                - collapse
                - dropdown
                - modal
                - scrollspy
                - tab
                - tooltip
                - popover
                - affix
            #configuration:
            #    data_api:
            #      - tooltip
            #      - popover

        # Bootstrap CSS
        bootstrap_css:
            include: true
            #path:
            #    local: ~
            #    cdn:   https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css
            #configuration:
            #    variables: ~

        # Font Awesome
        font_awesome:
            include: true
            #path:
            #    local: ~
            #    cdn: https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css

        # AngularJS
        angular:
            include: true
            plugins:
            #configuration:
            #    initialize: true
            #    app_name: AngularApp
            #    app_modules:
            #      - ngRoute