imports:
    - { resource: config_dev.yml }

# Framework Configuration
framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

# Doctrine Configuration
doctrine:
    dbal:
        host:     "%database_test_host%"
        port:     "%database_test_port%"
        dbname:   "%database_test_name%"
        user:     "%database_test_user%"
        password: "%database_test_password%"

# Swiftmailer Configuration
swiftmailer:
    disable_delivery: true
