imports:
    - { resource: config.yml }

framework:
    router:
        strict_requirements: true

monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: [!event]
        console:
            type:   console
            bubble: false
            channels: [!event, !doctrine]

#swiftmailer:
#    delivery_address: me@example.com
