# Routes for the public Area
music_tools_home:
    resource: "@MusicToolsHomeBundle/Resources/config/routing.yml"
    prefix:   /

# Routes for Theory
music_tools_theory:
    resource: "@MusicToolsTheoryBundle/Resources/config/routing.yml"
    prefix:   /theory

# Routes for the User workspace
music_tools_song_book:
    resource: "@MusicToolsSongBookBundle/Resources/config/routing.yml"
    prefix:   /my

music_tools_instrument:
    resource: "@MusicToolsInstrumentBundle/Resources/config/routing.yml"
    prefix:   /my

# Routes for User management
elorfin_user:
    resource: "@ElorfinUserBundle/Resources/config/routing.yml"
    prefix:   /

# Routes for the User community
music_tools_musician:
    resource: "@MusicToolsMusicianBundle/Resources/config/routing.yml"
    prefix:   /my/community
