music_tools_tuning:
    resource: "@MusicToolsTuningBundle/Resources/config/routing.yml"
    prefix:   /

music_tools_guitar:
    resource: "@MusicToolsGuitarBundle/Resources/config/routing.yml"
    prefix:   /

music_tools_note:
    resource: "@MusicToolsNoteBundle/Resources/config/routing.yml"
    prefix:   /
