music_tools_theory_interval:
    resource: MusicTools\TheoryBundle\Controller\IntervalController
    type:     rest

music_tools_theory_note:
    resource: MusicTools\TheoryBundle\Controller\NoteController
    type:     rest

music_tools_theory_degree:
    resource: MusicTools\TheoryBundle\Controller\DegreeController
    type:     rest

music_tools_theory_chord:
    resource: MusicTools\TheoryBundle\Controller\ChordController
    type:     rest

music_tools_theory_scale:
    resource: MusicTools\TheoryBundle\Controller\ScaleController
    type:     rest
