music_tools_theory_interval:
    resource: MusicTools\TheoryBundle\Controller\IntervalController
    type:     rest

music_tools_theory_note:
    resource: MusicTools\TheoryBundle\Controller\NoteController
    type:     rest
