services:
    # Managers
    music_tools_resource.manager.file:
        class: MusicTools\ResourceBundle\Manager\FileManager
        arguments:
            rootDir:   %kernel.root_dir%
            uploadDir: %upload_dir%

    # Listeners
    music_tools_resource.listener.file:
        class: MusicTools\ResourceBundle\EventListener\Entity\FileListener
        arguments:
            fileManager: @music_tools_resource.manager.file
        tags:
            - { name: doctrine.orm.entity_listener, entity: MusicTools\ResourceBundle\Entity\File, event: prePersist,  method: preUploadHandler }
            - { name: doctrine.orm.entity_listener, entity: MusicTools\ResourceBundle\Entity\File, event: preUpdate,   method: preUploadHandler }
            - { name: doctrine.orm.entity_listener, entity: MusicTools\ResourceBundle\Entity\File, event: postPersist, method: postPersist }
            - { name: doctrine.orm.entity_listener, entity: MusicTools\ResourceBundle\Entity\File, event: postUpdate,  method: postUpdate  }
            - { name: doctrine.orm.entity_listener, entity: MusicTools\ResourceBundle\Entity\File, event: postRemove,  method: postRemove  }

    # Twig extensions
    music_tools_resource.twig.resource_path_extension:
        class: MusicTools\ResourceBundle\Twig\ResourcePathExtension
        arguments:
            fileManager: @music_tools_resource.manager.file
        tags:
            - { name: twig.extension }
