services:
    music_tools_resource.listener.image:
        class: MusicTools\ResourceBundle\Entity\Listener\ImageListener
        # arguments: [@service_id, "plain_value", %parameter%]
        tags:
            -  { name: doctrine.entity_listener }