services:
    musician.twig.musician:
        class: MusicTools\MusicianBundle\Twig\MusicianExtension
        arguments:
            tokenStorage:  @security.token_storage
            objectManager: @doctrine.orm.entity_manager
        tags:
            - { name: twig.extension }

    musician.listener.user:
        class: MusicTools\MusicianBundle\EventListener\UserListener
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: kernel.event_listener, event: fos_user.registration.completed, method: onRegistrationConfirmed }