# Routes for Instrument
music_tools_instrument:
    resource: "@MusicToolsInstrumentBundle/Resources/config/routing.yml"
    type:     rest

# Routes for SongBook
music_tools_song_book:
    resource: "@MusicToolsSongBookBundle/Resources/config/routing.yml"
    type:     rest

# Routes for Theory
music_tools_theory:
    resource: "@MusicToolsTheoryBundle/Resources/config/routing.yml"
    type:     rest

# Routes for Lesson
music_tools_lesson:
    resource: "@MusicToolsLessonBundle/Resources/config/routing.yml"
    prefix:   /lesson

# Routes for Game
music_tools_game:
    resource: "@MusicToolsGameBundle/Resources/config/routing.yml"
    prefix:   /game

# Routes for Musician
music_tools_musician:
    resource: "@MusicToolsMusicianBundle/Resources/config/routing.yml"
    prefix:   /musician

# Routes for Forum
music_tools_forum:
    resource: "@MusicToolsForumBundle/Resources/config/routing.yml"
    prefix:   /forum

# Routes for Advertisement
music_tools_advertisement:
    resource: "@MusicToolsAdvertisementBundle/Resources/config/routing.yml"
    prefix:   /advert