# Routes for Instrument
music_tools_instrument:
    resource: "@MusicToolsInstrumentBundle/Controller/"
    type:     annotation

# Routes for SongBook
music_tools_song_book:
    resource: "@MusicToolsSongBookBundle/Controller/"
    type:     annotation

# Routes for Theory
music_tools_theory:
    resource: "@MusicToolsTheoryBundle/Controller/"
    type:     annotation

# Routes for Lesson
music_tools_lesson:
    resource: "@MusicToolsLessonBundle/Controller/"
    type:     annotation

# Routes for Game
music_tools_game:
    resource: "@MusicToolsGameBundle/Controller/"
    type:     annotation

# Routes for Musician
music_tools_musician:
    resource: "@MusicToolsMusicianBundle/Controller/"
    type:     annotation

# Routes for Forum
music_tools_forum:
    resource: "@MusicToolsForumBundle/Controller/"
    type:     annotation

# Routes for Advertisement
music_tools_advertisement:
    resource: "@MusicToolsAdvertisementBundle/Controller/"
    type:     annotation